---
argument_specs:
  main:
    short_description: Main entry point for the scoop role
    description:
      - This is the main entrypoint for the C(scoop) role.
      - This role will first validate that you have scoop installed.
    author:
      - Chun Pan Yung
    options:
      scoop_gui_apps:
        type: "bool"
        required: false
        default: false
        description:
          - Install GUI apps for general use case.
      scoop_dev_apps:
        type: "bool"
        required: false
        default: false
        description:
          - Install dev apps for developer use case.
