---
argument_specs:
  main:
    short_description: Base configurations for Windows.
    description:
      - Main entry point for base role.
    author:
      - Chun Pan Yung
    options:
      base_single_click:
        type: "bool"
        required: false
        default: false
        description:
          - Configure windows to use single click to open folders and files.
